lab6/Lab6/Entities/Asset.cs
namespace Lab6.Entities
{
    public class Asset
    {
        public int Asset_ID { get; set; }
        public string Asset_Type_Code { get; set; }
        public string Size_Code { get; set; }
        public string Asset_Name { get; set; }
        public string Other_Details { get; set; }


    }
}

lab6/Lab6/Entities/Assets_Life_Cycle_Events.cs
using System;

namespace Lab6.Entities
{
    public class Assets_Life_Cycle_Events
    {
        public int Asset_Life_Cycle_Event_ID { get; set; }
        public int Asset_ID { get; set; }
        public string Life_Cycle_Code { get; set; }

        public int Location_ID { get; set; }

        public int Party_ID { get; set; }

        public string Status_Code { get; set; }

        public DateTimeOffset Date_From { get; set; }
        public DateTimeOffset Date_To { get; set; }


    }
}

lab6/Lab6/Entities/Location.cs
namespace Lab6.Entities
{
    public class Location
    {
        public int Location_ID { get; set; }
        public string Location_Details { get; set; }
    }
}

lab6/Lab6/Controllers/DatabaseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using IdentityModel.Client;
using Lab6.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Lab6.Controllers
{
    public class DatabaseController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private HttpClient client;
        public DatabaseController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            var jsonToken = HttpContext.GetTokenAsync("access_token").GetAwaiter().GetResult();
            var client = _httpClientFactory.CreateClient();
            client.SetBearerToken(jsonToken);
            this.client = client;
        }
        public async Task<ViewResult> Assets()
        {
            var databaseHandler = new DatabaseHandler<Asset>(client, Tables.Assets);
            ViewBag.Assets = await databaseHandler.GetList();
            return View();
        }
        [HttpGet]
        public async Task<ViewResult> AssetsLifeCycleEvents()
        {
            var databaseHandler = new DatabaseHandler<Assets_Life_Cycle_Events>(client, Tables.AssetsLifeCycleEvents);
            ViewBag.Assets = await databaseHandler.GetList();
            return View();
        }

        [HttpGet]
        public async Task<ViewResult> Locations()
        {
            var databaseHandler = new DatabaseHandler<Location>(client, Tables.Locations);
            ViewBag.Entities = await databaseHandler.GetList();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> UpdateLocation(Location location)
        {
            var databaseHandler = new DatabaseHandler<Location>(client, Tables.Locations);
            await databaseHandler.Update(location);
            return RedirectToAction("Locations");
        }

        [HttpPost]
        public async Task<ActionResult> CreateLocation(Location location)
        {
            var databaseHandler = new DatabaseHandler<Location>(client, Tables.Locations);
            await databaseHandler.Create(location);
            return RedirectToAction("Locations");
        }
        [HttpPost]
        public async Task<ActionResult> DeleteLocation(Location location)
        {
            var databaseHandler = new DatabaseHandler<Location>(client, Tables.Locations);
            await databaseHandler.Delete(location.Location_ID);
            return RedirectToAction("Locations");
        }
        [HttpGet]
        public async Task<ViewResult> RefStatuses()
        {
            var databaseHandler = new DatabaseHandler<Ref_Status>(client, Tables.RefStatuses);
            ViewBag.Entities = await databaseHandler.GetList();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateRefStatus(Ref_Status location)
        {
            var databaseHandler = new DatabaseHandler<Ref_Status>(client, Tables.RefStatuses);
            await databaseHandler.Create(location);
            return RedirectToAction("RefStatuses");
        }

        [HttpPost]
        public async Task<ActionResult> UpdateRefStatus(Ref_Status location)
        {
            var databaseHandler = new DatabaseHandler<Ref_Status>(client, Tables.RefStatuses);
            await databaseHandler.Update(location);
            return RedirectToAction("RefStatuses");
        }
        [HttpPost]
        public async Task<ActionResult> DeleteRefStatus(Ref_Status location)
        {
            var databaseHandler = new DatabaseHandler<Ref_Status>(client, Tables.RefStatuses);
            await databaseHandler.Delete(location.Status_Code);
            return RedirectToAction("RefStatuses");
        }
    }
}

lab6/Lab6/Views/Database/Assets.cshtml
@using Lab6.Entities

@{
    ViewData["Title"] = "Assets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Asset

<div class="text-center">
    <h1 class="display-4">Assets</h1>
    @foreach (Asset asset in ViewBag.Assets)
    {
        <div>@asset.Asset_ID @asset.Asset_Name @asset.Other_Details</div>
    }
</div>

lab6/Lab6/Views/Database/AssetsLifeCycleEvents.cshtml
@using Lab6.Entities

@{
    ViewData["Title"] = "Assets Life Cycle Events";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Assets Life Cycle Events</h1>
    @foreach (Assets_Life_Cycle_Events asset in ViewBag.Assets)
    {
        <div>@asset.Asset_Life_Cycle_Event_ID @asset.Date_From @asset.Date_To</div>
    }
</div>

lab6/Lab6/Views/Database/Locations.cshtml
@using Lab6.Entities

@{
    ViewData["Title"] = "Locations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Location

<div class="text-center">
    <h1 class="display-4">Locations</h1>
    <form asp-controller="Database" asp-action="CreateLocation" method="post">
        <input type="hidden" asp-for="Location_ID" value="" /> Location Details <input asp-for="Location_Details" value="" /> 
        <button type="submit">Create</button>
    </form>
    @foreach (Location asset in ViewBag.Entities)
    {

        <form asp-controller="Database" asp-action="UpdateLocation" method="post">
            @asset.Location_ID <input type="hidden" asp-for="Location_ID" value="@asset.Location_ID" /> <input asp-for="Location_Details" value="@asset.Location_Details" /> 
            <button type="submit">Update</button>
        </form>
        <form asp-controller="Database" asp-action="DeleteLocation" method="post">
            <input type="hidden" value="@asset.Location_ID" asp-for="Location_ID" />
            <input type="hidden" value="@asset.Location_Details" asp-for="Location_Details" />
            <button type="submit">Delete</button>
        </form>
    }
</div>

lab6/Lab6/Views/Database/RefStatuses.cshtml
@using Lab6.Entities

@{
    ViewData["Title"] = "Ref Statuses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Ref_Status

<div class="text-center">
    <h1 class="display-4">Ref Statuses</h1>
    <form asp-controller="Database" asp-action="CreateRefStatus" method="post">
        StatusCode <input asp-for="Status_Code" value="" /> Status Description <input asp-for="Status_Description" value="" />
        <button type="submit">Create</button>
    </form>
    @foreach (Ref_Status asset in ViewBag.Entities)
    {
        <form asp-controller="Database" asp-action="UpdateRefStatus" method="post">
            @asset.Status_Code <input type="hidden" asp-for="Status_Code" value="@asset.Status_Code" /> <input asp-for="Status_Description" value="@asset.Status_Description" />
            <button type="submit">Update</button>
        </form>
        <form asp-controller="Database" asp-action="DeleteRefStatus" method="post">
            <input type="hidden" value="@asset.Status_Code" asp-for="Status_Code" />
            <input type="hidden" value="@asset.Status_Description" asp-for="Status_Description" />
            <button type="submit">Delete</button>
        </form>
    }
</div>